---
- name: "Creating multiple by checking folders"
  hosts: master
  tasks:
  - block:
    - name: "Checking folders"
      stat:
       path: "{{item}}"
      register: folder_stats
      with_items:
      - ["/var/www/html/AMBARI","/var/www/html/HDP","/var/www/html/HDP_UTIL","/var/www/html/HDP_GPL"]
    - name: "Creating multiple folders without disturbing previous permissions"
      file:
       path: "{{item.item}}"
       state: directory
       mode: 0755
       group: root
       owner: root
      when: item.stat.exists == false
      with_items:
      - "{{folder_stats.results}}"
...
