---
- hosts: master
  tasks:
  - name: HDP Version - HDP-3.1.0.0 creating manual local repo hdp.repo
    yum_repository:
      name: hdp
      description: HDP Version - HDP-3.1.0.0
      baseurl: http://master.hadoop.com/HDP/HDP/centos7/3.1.0.0-78
      gpgkey: http://master.hadoop.com/HDP/HDP/centos7/3.1.0.0-78/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
      gpgcheck: yes
      enabled: yes
...

